use_frameworks!

target 'RACSerialQueue_Example' do
  pod 'RACSerialQueue', :path => '../'

  target 'RACSerialQueue_Tests' do
    inherit! :search_paths
    pod 'RACSerialQueue', :path => '../'

    pod 'Kiwi'
  end
end
